### ISSUE TITLE
Random logging error

### ISSUE THREAD

**Issue by MartinP7r** [amir9480/vscode-laravel-extra-intellisense#23]
I have a custom logger provided via a laravel package that works fine otherwise, but randomly throws the below error when this extension is activated.  
Seems like there is something running in the background that uses the laravel cli but my custom handler can't be found (custom handler normally works fine for cli).
the two `[internal function]`line point to `VscodeLaravelExtraIntellisenseProvider`.

```log
[2020-07-13 09:03:14] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Authentication user provider [customauth] is not defined. at vendor/laravel/framework/src/Illuminate/Auth/CreatesUserProviders.php:42)
[stacktrace]
#0 vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(123): Illuminate\\Auth\\AuthManager->createUserProvider('users')
#1 vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(94): Illuminate\\Auth\\AuthManager->createSessionDriver('web', Array)
#2 vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(68): Illuminate\\Auth\\AuthManager->resolve('web')
#3 vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(297): Illuminate\\Auth\\AuthManager->guard()
#4 vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(239): Illuminate\\Auth\\AuthManager->__call('user', Array)
#5 vendor/martin/logger/src/DiscoHandler.php(23): Illuminate\\Support\\Facades\\Facade::__callStatic('user', Array)
#6 vendor/laravel/framework/src/Illuminate/Log/LogManager.php(126): Martin\\Logger\\DiscoHandler->__invoke(Object(Illuminate\\Log\\Logger), '')
#7 vendor/laravel/framework/src/Illuminate/Log/LogManager.php(103): Illuminate\\Log\\LogManager->tap('cli', Object(Illuminate\\Log\\Logger))
#8 vendor/laravel/framework/src/Illuminate/Support/helpers.php(1263): Illuminate\\Log\\LogManager->Illuminate\\Log\\{closure}(Object(Monolog\\Logger))
#9 vendor/laravel/framework/src/Illuminate/Log/LogManager.php(104): with(Object(Monolog\\Logger), Object(Closure))
#10 vendor/laravel/framework/src/Illuminate/Log/LogManager.php(90): Illuminate\\Log\\LogManager->get('cli')
#11 vendor/laravel/framework/src/Illuminate/Log/LogManager.php(583): Illuminate\\Log\\LogManager->driver()
#12 Command line code(1): Illuminate\\Log\\LogManager->__call('setHandlers', Array)
#13 [internal function]: VscodeLaravelExtraIntellisenseProvider->boot()
#14 vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#15 vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#16 vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#17 vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#18 vendor/laravel/framework/src/Illuminate/Foundation/Application.php(827): Illuminate\\Container\\Container->call(Array)
#19 vendor/laravel/framework/src/Illuminate/Foundation/Application.php(810): Illuminate\\Foundation\\Application->bootProvider(Object(VscodeLaravelExtraIntellisenseProvider))
#20 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(VscodeLaravelExtraIntellisenseProvider), 3)
#21 vendor/laravel/framework/src/Illuminate/Foundation/Application.php(811): array_walk(Array, Object(Closure))
#22 vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#23 vendor/laravel/framework/src/Illuminate/Foundation/Application.php(210): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#24 vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(322): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#25 vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#26 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#27 {main}
```

**Comment by amir9480** [comment]
@MartinP7r 

Hello

This extension also changes default logger.
https://github.com/amir9480/vscode-laravel-extra-intellisense/blob/master/src/helpers.ts#L61

And this is for preventing log errors when extension uses laravel application.
https://github.com/amir9480/vscode-laravel-extra-intellisense/issues/9

**Comment by MartinP7r** [comment]
> I also noticed something in your code that you are using session while this extension call laravel application using CLI. (Authentication user provider [customauth] is not defined) (martin/logger/src/DiscoHandler.php(23)).

Yeah, I'm injecting some extra data into my logging based on incoming http headers. I found some incompatibility with PHP7.4 in there which might have fixed my issue. I'll close this for now. Thanks for your help!
