### ISSUE TITLE
Call to undefined method Illuminate\Log\Writer::setHandlers()

### ISSUE THREAD

**Issue by pestopancake** [amir9480/vscode-laravel-extra-intellisense#26]
I'm getting this error logged (in sentry) every 30 seconds 🤔 :

```
Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Illuminate\Log\Writer::setHandlers()
#14 Command line code(1): VscodeLaravelExtraIntellisenseProvider::boot
#13 [internal](0): call_user_func_array
#12 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}
#11 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::callBoundMethod
#10 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::call
#9 /vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\Container::call
#8 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(792): Illuminate\Foundation\Application::bootProvider
#7 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Foundation\Application::Illuminate\Foundation\{closure}
#6 [internal](0): array_walk
#5 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(776): Illuminate\Foundation\Application::boot
#4 /vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Bootstrap\BootProviders::bootstrap
#3 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\Foundation\Application::bootstrapWith
#2 /vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(296): Illuminate\Foundation\Console\Kernel::bootstrap
#1 /vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(119): Illuminate\Foundation\Console\Kernel::handle
#0 Command line code(1): null
```

**Comment by amir9480** [comment]
Hi @pestopancake 

Which version of laravel you are using?

**Comment by pestopancake** [comment]
Hey @amir9480 

laravel v5.5.49
PHP 7.3.18

**Comment by amir9480** [comment]
First, I recommend you to update your laravel to the latest version.

Update Extension to version 0.3.3 and this error should be fixed.

**Comment by amir9480** [comment]
@pestopancake First, I recommend you to update your laravel to the latest version.

Update Extension to version 0.3.3 and this error should be fixed.
