### ISSUE TITLE
Extension Host Error: provider FAILED

### ISSUE THREAD

**Issue by ghost** [amir9480/vscode-laravel-extra-intellisense#67]
Hi! First of all, thanks for this awesome extension!

Unfortunately, over the past year or so, I cannot use it due to startup errors. I will paste the stack trace below:

```log
[exthost] [error] TypeError: Cannot read property 'length' of undefined
	at Function.parseFunction (c:\Users\0xADAD\.vscode-oss\extensions\amiralizadeh9480.laravel-extra-intellisense-0.6.2\dist\extension.js:1:117457)
	at Function.parseDocumentFunction (c:\Users\0xADAD\.vscode-oss\extensions\amiralizadeh9480.laravel-extra-intellisense-0.6.2\dist\extension.js:1:117865)
	at provideCompletionItems (c:\Users\0xADAD\.vscode-oss\extensions\amiralizadeh9480.laravel-extra-intellisense-0.6.2\dist\extension.js:1:133211)
	at K.provideCompletionItems (c:\Program Files\VSCodium\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:104497)
	at c:\Program Files\VSCodium\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:126396
	at be._withAdapter (c:\Program Files\VSCodium\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:116653)
	at be.$provideCompletionItems (c:\Program Files\VSCodium\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:126372)
	at n._doInvokeHandler (c:\Program Files\VSCodium\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:13812)
	at n._invokeHandler (c:\Program Files\VSCodium\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:13496)
	at n._receiveRequest (c:\Program Files\VSCodium\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:12107)
	at n._receiveOneMessage (c:\Program Files\VSCodium\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:10836)
	at c:\Program Files\VSCodium\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:89:8945
	at d.invoke (c:\Program Files\VSCodium\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
	at w.fire (c:\Program Files\VSCodium\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856)
	at c.fire (c:\Program Files\VSCodium\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:19017)
	at c:\Program Files\VSCodium\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:34266
	at d.invoke (c:\Program Files\VSCodium\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
	at w.fire (c:\Program Files\VSCodium\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856)
	at c.fire (c:\Program Files\VSCodium\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:19017)
	at s._receiveMessage (c:\Program Files\VSCodium\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:23598)
	at c:\Program Files\VSCodium\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:21132
	at d.invoke (c:\Program Files\VSCodium\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:145)
	at w.fire (c:\Program Files\VSCodium\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:58:1856)
	at w.acceptChunk (c:\Program Files\VSCodium\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:15848)
	at c:\Program Files\VSCodium\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:14978
	at Socket.T (c:\Program Files\VSCodium\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:13790)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by 3bd-ulrahman** [comment]
same issue
every thing work perfect until install database client extension

**Comment by amir9480** [comment]
@ghost Thanks for reporting. Will be fixed in next release.

**Comment by 3bd-ulrahman** [comment]
still not working when install database client extension
